In [ ]:
import pandas as pd

df = pd.read_csv('/content/sample_data/employees_large.csv')

avg_salary_by_dept = df.groupby('Department')['Salary'].mean()

print("Average Salary by Department:")
print(avg_salary_by_dept)

department_with_highest_salary = avg_salary_by_dept.idxmax()
highest_salary = avg_salary_by_dept.max()

print(f"\nDepartment with the highest average salary: {department_with_highest_salary}")
print(f"Highest average salary: ${highest_salary}")


Average Salary by Department:
Department
Engineering    125000.0
Finance         78000.0
HR              68000.0
IT              57750.0
Marketing       43750.0
Name: Salary, dtype: float64

Department with the highest average salary: Engineering
Highest average salary: $125000.0


In [ ]:
import pandas as pd

sales_df = pd.read_csv('/content/sample_data/sales_large.csv')

total_sales_by_product_region = sales_df.groupby(['Region', 'Product'])['Sales'].sum().reset_index()

highest_sales_product = total_sales_by_product_region.groupby('Product')['Sales'].sum().idxmax()
print(f"Product with the highest total sales across all regions: {highest_sales_product}")


Product with the highest total sales across all regions: Apples


In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C_add = np.add(A, B)
C_sub = np.subtract(A, B)
C_mul = np.dot(A, B)
C_elem_mul = np.multiply(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix A + B:\n", C_add)
print("Matrix A - B:\n", C_sub)
print("Matrix A * B (Matrix multiplication):\n", C_mul)
print("Element-wise multiplication A * B:\n", C_elem_mul)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix A + B:
 [[ 6  8]
 [10 12]]
Matrix A - B:
 [[-4 -4]
 [-4 -4]]
Matrix A * B (Matrix multiplication):
 [[19 22]
 [43 50]]
Element-wise multiplication A * B:
 [[ 5 12]
 [21 32]]


In [ ]:
import numpy as np

data = np.random.randn(10000)
mean_data = np.mean(data)
median_data = np.median(data)
std_dev_data = np.std(data)
min_data = np.min(data)
max_data = np.max(data)
greater_than_mean = np.sum(data > mean_data)
normalized_data = (data - min_data) / (max_data - min_data)

print(f"Mean: {mean_data}, Median: {median_data}, Standard Deviation: {std_dev_data}")
print(f"Min value: {min_data}, Max value: {max_data}")
print(f"Number of values greater than the mean: {greater_than_mean}")
print(f"Normalized dataset (first 10 values): {normalized_data[:10]}")


Mean: 0.0023789622879010455, Median: 0.0052692268961337715, Standard Deviation: 1.0079236527902704
Min value: -4.098524620797159, Max value: 3.541557272966696
Number of values greater than the mean: 5009
Normalized dataset (first 10 values): [0.69699583 0.33878326 0.62709319 0.59063642 0.55925943 0.54289649
 0.61080615 0.45627178 0.60331242 0.63553789]


In [ ]:
temperatures = [28, 32, 35, 31, 29, 30, 33, 36, 27, 25, 34, 30, 29, 37, 38, 26, 31, 35, 33, 32, 36, 34, 29, 28, 27, 35, 32, 30, 31, 33]

above_32 = [temp for temp in temperatures if temp > 32]

classification = [(temp, 'Hot' if temp > 35 else 'Warm' if temp >= 30 else 'Cool') for temp in temperatures]
avg_temp = np.mean(temperatures)
temp_diffs = [temp - avg_temp for temp in temperatures]

print(f"Temperatures above 32°C: {above_32}")
print(f"Temperature classifications: {classification}")
print(f"Temperature differences from the average: {temp_diffs}")


Temperatures above 32°C: [35, 33, 36, 34, 37, 38, 35, 33, 36, 34, 35, 33]
Temperature classifications: [(28, 'Cool'), (32, 'Warm'), (35, 'Warm'), (31, 'Warm'), (29, 'Cool'), (30, 'Warm'), (33, 'Warm'), (36, 'Hot'), (27, 'Cool'), (25, 'Cool'), (34, 'Warm'), (30, 'Warm'), (29, 'Cool'), (37, 'Hot'), (38, 'Hot'), (26, 'Cool'), (31, 'Warm'), (35, 'Warm'), (33, 'Warm'), (32, 'Warm'), (36, 'Hot'), (34, 'Warm'), (29, 'Cool'), (28, 'Cool'), (27, 'Cool'), (35, 'Warm'), (32, 'Warm'), (30, 'Warm'), (31, 'Warm'), (33, 'Warm')]
Temperature differences from the average: [-3.533333333333335, 0.466666666666665, 3.466666666666665, -0.533333333333335, -2.533333333333335, -1.533333333333335, 1.466666666666665, 4.466666666666665, -4.533333333333335, -6.533333333333335, 2.466666666666665, -1.533333333333335, -2.533333333333335, 5.466666666666665, 6.466666666666665, -5.533333333333335, -0.533333333333335, 3.466666666666665, 1.466666666666665, 0.466666666666665, 4.466666666666665, 2.466666666666665, -2.533333